version: "3.8"
#declarar las 3 imagenes para que interactuen entre si
#notacion yml definir la estructura 
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      #volumen de base de datos
      - ./db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: always
    env_file: ./.env
    ports:
      - 8081:8080
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false", "spring.datasource.username" : "$MYSQLDB_USER", "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD", "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect", "spring.jpa.hibernate.ddl-auto" : "update" }'
    volumes:
      - .m2:/root/.m2
      - .:/app
    stdin_open: true
    tty: true

  # phpmyadmin user: root password: root
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD

volumes:
  db:
  .m2: